//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductStoresPip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
       [Key]
        public int id { get; set; }
        [Required(ErrorMessage ="Product name is required.")]
        [DisplayName("Product1")]
        public string Product1 { get; set; }
        [Required(ErrorMessage ="Category Required.")]
        [DisplayName("Category")]
        public string Category { get; set; }
        [Required(ErrorMessage = "Price Required.")]
        [DisplayName("Price")]
        public decimal Price { get; set; }
        public string Currency { get; set; }
        public int Units { get; set; }
    }
}
